[phases.setup]
nixPkgs = ["nodejs-18_x", "yarn"]

[phases.install]
cmds = ["yarn set version berry", "yarn install --ignore-engines"]

[phases.build]
cmds = ["yarn build"]

[phases.start]
cmd = "yarn start"
